### ISSUE TITLE
PatStruct should be supported

### ISSUE THREAD

**Issue by kmizu** [dwango/fialyzer#46]
Currently, ast_intf.ml has `PatStruct of string list * expr`, which means struct pattern.  However, it cannot be implemented since it seems that obeam doesn't support such pattern currently.

**Comment by kmizu** [comment]
Related PR: https://github.com/dwango/fialyzer/pull/45

**Comment by amutake** [comment]
obeam issue: https://github.com/yutopp/obeam/issues/16
