### ISSUE TITLE
Support match expr

### ISSUE THREAD

**Issue by amutake** [dwango/fialyzer#81]
ref: #78 

`Pattern = Expression` form is called `match expression` and `=` operator is called `match operator`.
(NOTICE: `case E of ... end` is `case expression`, not `match expression`)

but match expr is so crazy...

```
Erlang/OTP 21 [erts-10.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Eshell V10.1.3  (abort with ^G)
1> {A, B} = {1, [Z = 2]}, Z.
2
```

**Comment by yoshihiro503** [comment]
So crazy...

What about the idea of skipping if it is complicated except in the following cases?
```erlang
<pattern_1> = <pattern_2> = ... = <pattern_n> = <expr_1>,
<expr_2>
```

This should be:
```erlang
case [expr_1] of
  [pattern_1] ->
  case [expr_1] of
    [pattern_2] ->
    ...
      case [expr_n] of
        [pattern_n] -> [expr_2]
      end
    ...
  end
end
```
