### ISSUE TITLE
MFA should be record

### ISSUE THREAD

**Issue by kmizu** [dwango/fialyzer#87]
Currently, the data constructor MFA is defined as follows:

```ocaml
type expr =
   ...
    | MFA of expr * expr * expr
```

However, using 3-tuple of `expr` is not good for readability.  So,  I think that it should be:

```ocaml
type expr =
     | MFA of { module_name: expr, function_name: expr, arity: expr }
```

How do you think? @yoshihiro503 @amutake

**Comment by yoshihiro503** [comment]
+1
