### ISSUE TITLE
Support list expression

### ISSUE THREAD

**Issue by yoshihiro503** [dwango/fialyzer#90]
Add two variants to Ast_intf.expr
- ListNil
- ListCons of expr * expr

and fix conversions From_erlang.expr_of_erlang_expr
- string literal should be `ListCons` or `ListNil`
- `[]` shold be `ListNil`
- `[<expr> | <expr>]` and `[<expr>, ...]` shold be `ListCons`

Don't support:
- list patterns
- list comprehension expression

**Comment by amutake** [comment]
I'll do this

**Comment by amutake** [comment]
Oops this issue is done by #120. close.
